### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by MBratkowski** [JanuszHain/SocialMediaWatcher#1]
- You don't have any application structure. You could separate different type classes. Example if you have a adapteres class you create a new package with name 'adapter, if you have a model class put is in 'model' package. When you separate your classes to package your application structure are better, testable, maintainability.
- If you use a Rx you do not use a EventBus library.
- Your project do not use a Object Programming Paradidgmats, like abstraction or composition. 
- Use a Threads to manage task is a bad idea when you have a Rx library.
- Your application are not separate to corners, you don't have a application layers like - model, view or presenter. Read more in topic `Android MVP design pattern`.

**Comment by JanuszHain** [comment]
Thank you for tips, will for sure look into it and improve my future programming

**Comment by JanuszHain** [comment]
Also could you please give me example of abstraction and composition for my project? As I understand other tips, this one is not so clear for me, as I don't see a reason in my code to implement abstraction. And about composition I am not sure too. 
Your help would be much appreciated.

Thanks in advance

**Comment by JanuszHain** [comment]
Okay, nevermind, I found out why abstraction and composition is important. I will try to rewrite code in the way to make it cleaner and easier for maintenance. And also, after that, new features sticking to the rules!

Thanks again for tips!
Janusz Hain
